### ISSUE TITLE
Package/compress model artifacts on COS

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Audio-Classifier#4]
The [checkpoint] assets are currently stored in individual files on COS, e.g. 
`http://max-assets.s3-api.us-geo.objectstorage.softlayer.net/audioset/vggish_model.ckpt`
`http://max-assets.s3-api.us-geo.objectstorage.softlayer.net/audioset/vggish_pca_params.npz`. The individual files should be packaged and compressed in a tar.gz archive, following the approach used by other models. Refer to https://github.com/IBM/MAX-Object-Detector/blob/master/Dockerfile for an example.

Benefits:
* Only a single file needs to be downloaded (less work)
* Artifacts are compressed, potentially reducing the time it takes to download them

**Comment by bdwyer2** [comment]
@kmh4321 you can probably duplicate this PR (https://github.com/IBM/MAX-Audio-Embedding-Generator/pull/4) on this repository.

**Comment by bdwyer2** [comment]
Didn't realize that you had more files, I guess you should zip everything together.

**Comment by MLnick** [comment]
It'll be cleaner to add all your required files to 1 archive. We should have an archive per model for consistency and to keep things cleanly separated.
