### ISSUE TITLE
Error in building Docker Image in Windows

### ISSUE THREAD

**Issue by shfaizan** [IBM/MAX-Audio-Classifier#60]
Hello, I have tried MAX audio Classifier in Ubuntu and it works effortlessly. 

I want to know can we use it in Windows also when I try to build the image I got the following error 
`sha512sum: 'assets/classifier_model.h5'$'\r': No such file or directory
sha512sum: 'assets/vggish_model.ckpt'$'\r': No such file or directory`
![image](https://user-images.githubusercontent.com/39994105/90319781-e4fb1e00-df58-11ea-905e-9313e76d8811.png)
(Here is the Image of error)

**Comment by bdwyer2** [comment]
Can you comment out line 32 in the Dockerfile (`RUN sha512sum -c sha512sums.txt`) then start the container with `docker run -it -p 5000:5000 max-audio classifier bash`.

Once you have the container running see if the files exist in the `assets/` directory.

**Comment by xuhdev** [comment]
Your sha512sums.txt file seems to have CRLF line endings, which aren't expected. This is likely due to your Windows git configuration. Try to run

    git config --global core.autocrlf false

and refresh the repository (recloning is probably the easiest way), and see whether the issue persists.

**Comment by bdwyer2** [comment]
@shfaizan did this resolve your problem? If not please feel free to re-open this issue.
